### ISSUE TITLE
AttributeError: 'Engine' object has no attribute 'execute'

### ISSUE THREAD

**Issue by Lukysoon** [Vuizur/tatoeba-to-anki#13]
Hi, it seems like very nice tool. I would like to run in but it throws error.

I'm running it in venv. Normal installation.

Thank you very much

**Comment by Vuizur** [comment]
I know that it currently only works with Python 3.10 (and not with newer
versions). Have you tried it with that?

Dne pá 1. 11. 2024 22:14 uživatel Lukas Starenko ***@***.***>
napsal:

**Comment by Lukysoon** [comment]
I does'n work for me still.
What version of sqlalchemy and tatoebatools do you have installed pelase?

'Engine' object has no attribute 'execute' is problem of sqlalchemy 2.x.x 
Engine.execute()  work for 1.4.x version but not for sqlalchemy 2.x.x

Thank you

**Comment by Lukysoon** [comment]
Could you please share freeezed requirements.txt

Thank you
